# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sdifi.events.v1alpha import event_pb2 as sdifi_dot_events_dot_v1alpha_dot_event__pb2


class EventServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Watch = channel.unary_stream(
                '/sdifi.events.v1alpha.EventService/Watch',
                request_serializer=sdifi_dot_events_dot_v1alpha_dot_event__pb2.WatchRequest.SerializeToString,
                response_deserializer=sdifi_dot_events_dot_v1alpha_dot_event__pb2.WatchResponse.FromString,
                )


class EventServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=sdifi_dot_events_dot_v1alpha_dot_event__pb2.WatchRequest.FromString,
                    response_serializer=sdifi_dot_events_dot_v1alpha_dot_event__pb2.WatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdifi.events.v1alpha.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sdifi.events.v1alpha.EventService/Watch',
            sdifi_dot_events_dot_v1alpha_dot_event__pb2.WatchRequest.SerializeToString,
            sdifi_dot_events_dot_v1alpha_dot_event__pb2.WatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
